### ISSUE TITLE
Cannot open in BETA 908

### ISSUE THREAD

**Issue by wqweto** [fafalone/ucWebView2#4]
On loading all projects barf
```
---------------------------
{566498A8-8F6E-4BC7-869E-2A50C8CB460B}
---------------------------
Unable to load library.
---------------------------
OK   
---------------------------
```
and 
```
---------------------------
{AA5DF978-0351-48DB-9F35-3F83DEF5FBB7}
---------------------------
Unable to load library.
---------------------------
OK   
---------------------------
```
. . . and then DIAGNOSTICS pane is full of with unrecognized symbols.

Is there a chance I would be able to make it compile or will have to wait for a fix?

**Comment by fafalone** [comment]
Should be fixed now. All the project files have been updated to use the WebView2 package from tB 908 and to link against WinDevLib 9.2+ (ByVal UDTs).

**Comment by wqweto** [comment]
Btw, can you post x86 and x64 compiled binaries in Releases here?

Still having problems compiling the .twinproj files and I want to test the user-control in VB6.

**Comment by fafalone** [comment]
The ocx builds from the current tB version aren't working (not in tB itself either, though it works as a .tbcontrol in project). So I could post binaries if you want but they'd be from old versions.

**Comment by wqweto** [comment]
I guess if not possible to test with current build an old build of the OCXs will be helpful too.

**Comment by fafalone** [comment]
Wayne fixed the one bug and hopefully he'll get to the other soon (see [Discord post](https://discord.com/channels/927638153546829845/1446965553817190542)), it's affecting numerous controls so hopefully a high priority. In the mean time sure I'll post a binary from an earlier tB version later today.

**Comment by fafalone** [comment]
This is the original version compiled with a tB version from when it was released (Beta 710). Working in VB6.

Registers as ZWebView2.

[ucWebView2Old.zip](https://github.com/user-attachments/files/24055983/ucWebView2Old.zip)
